### ISSUE TITLE
ngModel support

### ISSUE THREAD

**Issue by seth2810** [danprince/ng-picky#10]

**Comment by danprince** [comment]
What value should be bound?

The color object, hex string? Or should it be configurable based on another directive?

**Comment by seth2810** [comment]
Initially, I thought it would be a hexadecimal value, and all internal conversion in the color object would occur within the directive.

**Comment by danprince** [comment]
Yeah, I guess that could work. If the model binds the hex value, then the other filters can be converted over to convert from a hex string, to another color format.

**Comment by seth2810** [comment]
Sounds good... A little later I will try to implement this functionality. Now I see only one problem, the color conversion in position on the canvas.

**Comment by danprince** [comment]
Cool. When I get a spot of free time, I'll finish writing up a set of unit tests. Can work backwards from there to fix those conversion bugs.
